<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-IKS9SD1L" failures="1" tests="5" name="TestNGPrograms.NewEdgeTest" time="16.954" errors="0" timestamp="2022-07-29T20:21:43 IST" skipped="0">
  <testcase classname="TestNGPrograms.NewEdgeTest" name="launcgEdge" time="10.755"/>
  <system-out/>
  <testcase classname="TestNGPrograms.NewEdgeTest" name="loginkite" time="2.673"/>
  <system-out/>
  <testcase classname="TestNGPrograms.NewEdgeTest" name="loginkitepin" time="3.360"/>
  <system-out/>
  <testcase classname="TestNGPrograms.NewEdgeTest" name="CheckTitleTest" time="0.016">
    <failure message="expected [Dashboard / Kite] but found [Kite - Zerodha&#039;s fast and elegant flagship trading platform]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Dashboard / Kite] but found [Kite - Zerodha's fast and elegant flagship trading platform]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at TestNGPrograms.NewEdgeTest.CheckTitleTest(NewEdgeTest.java:40)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- CheckTitleTest -->
  <system-out/>
  <testcase classname="TestNGPrograms.NewEdgeTest" name="teardown" time="0.150"/>
  <system-out/>
</testsuite> <!-- TestNGPrograms.NewEdgeTest -->
